

public class SabHtml {
	public static String Write(String name, String phone, String planet)
	{
		String sabHtml ="<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "	<meta charset=\"UTF-8\">\r\n"
				+ "	<link rel=\"stylesheet\" href=\"./style/StyleSabmit.css\">\r\n"
				+ "	<title>Insert title here</title>\r\n"
				+ "	<link href=\"http://fonts.cdnfonts.com/css/roboto\" rel=\"stylesheet\">\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "	<header class=\"header\">\r\n"
				+ "        <nav class=\"nav-bar secondary-text\">\r\n"
				+ "            <div class=\"nav-bar-wrapper\">\r\n"
				+ "                <div class=\"nav-logo-wrapper\">\r\n"
				+ "                    <a class=\"nav-logo\" href = \"./index.html\"></a>\r\n"
				+ "                    <span class=\"nav-title\">My Document</span>\r\n"
				+ "                </div>\r\n"
				+ "\r\n"
				+ "                <div class=\"nav-menu-wrapper\">\r\n"
				+ "                    <span class=\"nav-menu-item\">Про нас</span>\r\n"
				+ "                    <a href=\"./hendels.html\" class=\"nav-menu-item\" >Оператори</a>\r\n"
				+ "                    <span class=\"nav-menu-item\">Новини</span>\r\n"
				+ "                    <i class=\"nav-menu-icon\"></i>\r\n"
				+ "                </div>\r\n"
				+ "\r\n"
				+ "                <div class=\"menu-button\"></div>\r\n"
				+ "            </div>\r\n"
				+ "        </nav>\r\n"
				+ "    </header>\r\n"
				+ "	\r\n"
				+ "	<div class=\"page-wrapper\">\r\n"
				+ "	    <section class=\"registration-section\">\r\n"
				+ "	        <div class=\"registration-form-wrapper\">\r\n"
				+ "	\r\n"
				+ "	            <div class=\"form-card flex-column\">\r\n"
				+ "	                <div class=\"form-wrapper\">\r\n"
				+ "	\r\n"
				+ "	                    <h2 class=\"form-title\">Ви успішно\r\n"
				+ "	                       <span id=\"text-to-change\">Зареєструвалися</span></h2>\r\n"
				+ "\r\n"
				+ "                        <p class=\"form-card-text\">Місце в черзі: </p>\r\n"
				+ "                        <p class=\"form-card-text\">Ім'я: "+name+"</p>\r\n"
				+ "                        <p class=\"form-card-text\">Телефон: "+phone+"</p>\r\n"
				+ "                        <p class=\"form-card-text\">Планета: "+planet+"</p>\r\n"
				+ "                        <p class=\"form-card-text\">Стан: </p>\r\n"
				+ "  \r\n"
				+ "	                </div>\r\n"
				+ "	           </div>\r\n"
				+ "	        </div>\r\n"
				+ "	    </section>\r\n"
				+ "	</div>\r\n"
				+ "	\r\n"
				+ "	<footer class=\"footer secondary-text\">\r\n"
				+ "        <span class=\"footer-credentials\">\r\n"
				+ "            © 2022 My Document. Всі права захищені.\r\n"
				+ "        </span>\r\n"
				+ "    </footer>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		return sabHtml;
	}
}
